service: subwayWTF

provider:
  name: aws
  runtime: python3.6

package:
  exclude:
    - venv

functions:
  twitter:
    handler: 6hours.6hours

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    zip: true